{% set name = "pep8-naming" %}
{% set version = "0.12.0" %}
{% set sha256 = "1f9a3ecb2f3fd83240fd40afdd70acc89695c49c333413e49788f93b61827e12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - flake8 >=3.9.1
    - flake8-polyfill >=1.0.2,<2

test:
  commands:
    - 'flake8 --version | grep naming:'

about:
  home: https://github.com/PyCQA/pep8-naming
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Plug-in for flake 8 to check the PEP-8 naming conventions
  dev_url: https://github.com/PyCQA/pep8-naming

extra:
  recipe-maintainers:
    - dopplershift
    - jakirkham
    - sigmavirus24
