{% set name = "pep8-naming" %}
{% set version = "0.10.0" %}
{% set sha256 = "f3b4a5f9dd72b991bf7d8e2a341d2e1aa3a884a769b5aaac4f56825c1763bf3a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  build:
    - python
    - pip

  run:
    - python
    - flake8
    - flake8-polyfill >=1.0.2,<2

test:
  commands:
    - 'flake8 --version | grep naming:'

about:
  home: https://github.com/PyCQA/pep8-naming
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Plug-in for flake 8 to check the PEP-8 naming conventions
  dev_url: https://github.com/PyCQA/pep8-naming

extra:
  recipe-maintainers:
    - dopplershift
    - jakirkham
    - sigmavirus24
