{% set name = "pep8-naming" %}
{% set version = "0.13.3" %}
{% set sha256 = "1705f046dfcd851378aac3be1cd1551c7c1e5ff363bacad707d43007877fa971" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip

  run:
    - python >=3.7
    - flake8 >=3.9.1

test:
  commands:
    - 'flake8 --version | grep naming:'

about:
  home: https://github.com/PyCQA/pep8-naming
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Plug-in for flake 8 to check the PEP-8 naming conventions
  dev_url: https://github.com/PyCQA/pep8-naming

extra:
  recipe-maintainers:
    - dopplershift
    - jakirkham
    - sigmavirus24
