{% set name = "pep8-naming" %}
{% set version = "0.7.0" %}
{% set sha256 = "624258e0dd06ef32a9daf3c36cc925ff7314da7233209c5b01f7e5cdd3c34826" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  number: 0

requirements:
  build:
    - python
    - pip

  run:
    - python
    - flake8
    - flake8-polyfill >=1.0.2,<2

test:
  commands:
    - "flake8 --version | grep naming:"

about:
  home: https://github.com/PyCQA/pep8-naming
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Plug-in for flake 8 to check the PEP-8 naming conventions'
  dev_url: https://github.com/PyCQA/pep8-naming

extra:
  recipe-maintainers:
    - dopplershift
    - jakirkham
    - sigmavirus24
