travis:
  secure:
    BINSTAR_TOKEN: akwh6c4ZCflzVsU+xs2udXpDtN7H9j0uA0EcMRZZgoqshZ8Aq8Vam/ngO1YfIlb8oh+7UP8NomY3Kv/eLySqCSdkUim87z66Mh8nqylFuk71czisZelCBW7spZQID5QNbNdYVPLROe6w6XqYOpRW3QGA4iI/eCYAynZXM08tTyQRdYivfJpT7zNzrxV+qgq33GZsSEMpnJcXl0xOs5TQsYA+ofDP3E78GxoMaG33wiyPHrQ6bwe+xkjznV+eTatUpyyZk62bFEHAWF28eaYMEYnayEZPR+MJlX+unzABxAv60ErwqU+6Z3zLCcQYEXe4PRDuEwpYuSGFuvypsdwFXnJA8llx1JywsEgnnPuHco+TFfyCYNOeof+S11A8sjdiGVfGAOdd/YPtvmuPEBzlg8PY9I0YUZ54a3wElJBpeeX/JE2uwHYBGGWtDDbmir1qHmO+jHfbUcOEHerAQ67Lo2U71LEuyRx3Z205hvv6nj1pwNkdRq4jcgxiL4ja4puS6hp4BRs4rdkc1YxmHHAbXljT4asD0XJ/dh5OrNDd8p5n3c8u2jUb1vwo6+VoZmzLW7k+yj+oz5uLMUREIvmDY1JVdpWILUWcDUV6UYTz+VfOIxFeSZD0AJ3Xev1ZS/+of7uwfWSWTbF5KS11XG7qFbZba4FbNj2uEL7wWkgjY8o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
